# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_1:
    name: web Crawl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Delete Artifact
      uses: geekyeggo/delete-artifact@v1
      with:
        name: repository
#     - name: Build with Maven
#       run: mvn -B install --file web-crawler/pom.xml
    - name: runMainMethod
      working-directory: web-crawler/
      run: mvn compile exec:java
    - name: getDir
      run: pwd
    - uses: actions/upload-artifact@v2
      with:
        name: repository
        path: web-crawler/repository/

  job_2:
    name: Noise removal
    needs: [job_1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      working-directory: noise-remover/
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python noise_remover.py
